<?php

namespace Database\Seeders;

use App\Enums\Currency;
use App\Enums\ProductType as ProductTypeEnum;
use App\Enums\ResourceType as ResourceTypeEnum;
use App\Models\ProductType;
use App\Models\ResourceType;
use Exception;
use RuntimeException;
use Webkul\Product\Models\Product;
use Webkul\Product\Models\ProductGroup;

class ProductSeeder extends BaseSeeder
{
    public function run(): void
    {
        $rows = [
            [
                'external_id'   => '1000',
                'productnaam'   => 'MRI Schedel exclusief CM',
                'omschrijving'  => 'MRI scan van de schedel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Schedel (los)',
            ],
            [
                'external_id'   => '1001',
                'productnaam'   => 'MRI Schedel inclusief CM',
                'omschrijving'  => 'MRI scan van de schedel, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '750,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Schedel (los)',
            ],
            [
                'external_id'   => '1002',
                'productnaam'   => 'MRI Hypofyse  inclusief CM',
                'omschrijving'  => 'MRI scan van de hypofyse, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '750,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Schedel (los)',
            ],
            [
                'external_id'   => '1003',
                'productnaam'   => 'MRI Schedel en Carotiden inclusief CM',
                'omschrijving'  => 'MRI scan van de schedel en hersenaanvoerende bloedvaten, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '750,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Schedel en Carotiden',
            ],
            [
                'external_id'   => '1004',
                'productnaam'   => 'MRI Hals weke delen',
                'omschrijving'  => 'MRI scan van de weke delen van de hals',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '281,00',
                'verkoopprijs'  => '750,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Hals weke delen',
            ],
            [
                'external_id'   => '1005',
                'productnaam'   => 'CT Schedel exclusief CM',
                'omschrijving'  => 'CT scan van de schedel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Schedel (los)',
            ],
            [
                'external_id'   => '1006',
                'productnaam'   => 'CT Schedel inclusief CM',
                'omschrijving'  => 'CT scan van de schedel, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '750,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Schedel (los)',
            ],
            [
                'external_id'   => '1007',
                'productnaam'   => 'CT Neustussenschot',
                'omschrijving'  => 'CT Neustussenschot',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Schedel (los)',
            ],
            [
                'external_id'   => '1008',
                'productnaam'   => 'CT Schedel en carotiden inclusief CM',
                'omschrijving'  => 'CT scan van de schedel en hersenaanvoerende bloedvaten, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '750,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Schedel en Carotiden',
            ],
            [
                'external_id'   => '1009',
                'productnaam'   => 'CT van de Hals weke delen',
                'omschrijving'  => 'CT van de Hals weke delen',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Hals weke delen',
            ],
            [
                'external_id'   => '1010',
                'productnaam'   => 'MRI Carotiden inclusief CM',
                'omschrijving'  => 'MRI scan van de hersenaanvoerende bloedvaten, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '220,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Carotiden',
            ],
            [
                'external_id'   => '1011',
                'productnaam'   => 'MRI Bekken en bloedvaten been inclusief CM',
                'omschrijving'  => 'MRI scan van het bekken en de bloedvaten naar de benen, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Bloedvaten',
            ],
            [
                'external_id'   => '1012',
                'productnaam'   => 'MRI Lichaamangiografie inclusief CM',
                'omschrijving'  => 'MRI scan van het gehele slagaderstelsel, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '750,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Bloedvaten',
            ],
            [
                'external_id'   => '1013',
                'productnaam'   => 'CT Angiografie Abdomen inclusief CM',
                'omschrijving'  => 'CT Angiografie van de onder- en bovenbuik (abdomen), inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Bloedvaten',
            ],
            [
                'external_id'   => '1014',
                'productnaam'   => 'CT Bekken en bloedvaten been inclusief CM',
                'omschrijving'  => 'CT scan van het bekken en de bloedvaten naar de benen, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '750,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Bloedvaten',
            ],
            [
                'external_id'   => '1015',
                'productnaam'   => 'CT Buik angiografie (Aorta) inclusief CM',
                'omschrijving'  => 'CT scan van de buikaorta, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Bloedvaten',
            ],
            [
                'external_id'   => '1016',
                'productnaam'   => 'CT Carotiden inclusief CM',
                'omschrijving'  => 'CT scan van de hersenaanvoerende bloedvaten, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Carotiden',
            ],
            [
                'external_id'   => '1017',
                'productnaam'   => 'MRI Schouder exclusief CM',
                'omschrijving'  => 'MRI scan van de schouder',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Schouder',
            ],
            [
                'external_id'   => '1018',
                'productnaam'   => 'MRI Schouder inclusief CM',
                'omschrijving'  => 'MRI scan van de schouder, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Schouder',
            ],
            [
                'external_id'   => '1019',
                'productnaam'   => 'MRI Elleboog exclusief CM',
                'omschrijving'  => 'MRI scan van de elleboog',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Elleboog',
            ],
            [
                'external_id'   => '1020',
                'productnaam'   => 'MRI Elleboog inclusief CM',
                'omschrijving'  => 'MRI scan van de elleboog, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Elleboog',
            ],
            [
                'external_id'   => '1021',
                'productnaam'   => 'MRI Pols exclusief CM',
                'omschrijving'  => 'MRI scan van de pols',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Pols',
            ],
            [
                'external_id'   => '1022',
                'productnaam'   => 'MRI Pols inclusief CM',
                'omschrijving'  => 'MRI scan van de pols, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Pols',
            ],
            [
                'external_id'   => '1023',
                'productnaam'   => 'MRI Hand exclusief CM',
                'omschrijving'  => 'MRI scan van de hand',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Hand',
            ],
            [
                'external_id'   => '1024',
                'productnaam'   => 'MRI Hand inclusief CM',
                'omschrijving'  => 'MRI scan van de hand, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Hand',
            ],
            [
                'external_id'   => '1025',
                'productnaam'   => 'MRI Heup exclusief CM',
                'omschrijving'  => 'MRI scan van de heup',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Heup',
            ],
            [
                'external_id'   => '1026',
                'productnaam'   => 'MRI Heup inclusief CM',
                'omschrijving'  => 'MRI scan van de heup, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Heup',
            ],
            [
                'external_id'   => '1027',
                'productnaam'   => 'MRI Knie exclusief CM',
                'omschrijving'  => 'MRI scan van de knie',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Knie',
            ],
            [
                'external_id'   => '1028',
                'productnaam'   => 'MRI Knie inclusief CM',
                'omschrijving'  => 'MRI scan van de knie, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Knie',
            ],
            [
                'external_id'   => '1029',
                'productnaam'   => 'MRI Enkel exclusief CM',
                'omschrijving'  => 'MRI scan van de enkel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Enkel',
            ],
            [
                'external_id'   => '1030',
                'productnaam'   => 'MRI Enkel inclusief CM',
                'omschrijving'  => 'MRI scan van de enkel, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Enkel',
            ],
            [
                'external_id'   => '1031',
                'productnaam'   => 'MRI Voet exclusief CM',
                'omschrijving'  => 'MRI scan van de voet',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Voet',
            ],
            [
                'external_id'   => '1032',
                'productnaam'   => 'MRI Voet inclusief CM',
                'omschrijving'  => 'MRI scan van de voet, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Voet',
            ],
            [
                'external_id'   => '1033',
                'productnaam'   => 'MRI Bekken exclusief contrastmiddel',
                'omschrijving'  => 'MRI scan van het bekken, exclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Bekken ',
            ],
            [
                'external_id'   => '1034',
                'productnaam'   => 'CT Voet exclusief CM',
                'omschrijving'  => 'CT scan van de voet',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Voet',
            ],
            [
                'external_id'   => '1035',
                'productnaam'   => 'CT Voet inclusief CM',
                'omschrijving'  => 'CT scan van de voet, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Voet',
            ],
            [
                'external_id'   => '1036',
                'productnaam'   => 'CT Schouder exclusief CM',
                'omschrijving'  => 'CT scan van de schouder',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Schouder',
            ],
            [
                'external_id'   => '1037',
                'productnaam'   => 'CT Schouder inclusief CM',
                'omschrijving'  => 'CT scan van de schouder, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Schouder',
            ],
            [
                'external_id'   => '1038',
                'productnaam'   => 'CT Knie exclusief CM',
                'omschrijving'  => 'CT scan van de knie',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Knie',
            ],
            [
                'external_id'   => '1039',
                'productnaam'   => 'CT Knie inclusief CM',
                'omschrijving'  => 'CT scan van de knie, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Knie',
            ],
            [
                'external_id'   => '1040',
                'productnaam'   => 'CT Heup exclusief CM',
                'omschrijving'  => 'CT scan van de heup',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Heup',
            ],
            [
                'external_id'   => '1041',
                'productnaam'   => 'CT Heup inclusief CM',
                'omschrijving'  => 'CT scan van de heup, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Heup',
            ],
            [
                'external_id'   => '1042',
                'productnaam'   => 'CT Pols exclusief CM',
                'omschrijving'  => 'CT scan van de pols',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Pols',
            ],
            [
                'external_id'   => '1043',
                'productnaam'   => 'CT Pols inclusief CM',
                'omschrijving'  => 'CT scan van de pols, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Pols',
            ],
            [
                'external_id'   => '1044',
                'productnaam'   => 'CT Enkel exclusief CM',
                'omschrijving'  => 'CT scan van de enkel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Enkel',
            ],
            [
                'external_id'   => '1045',
                'productnaam'   => 'CT Enkel inclusief CM',
                'omschrijving'  => 'CT scan van de enkel, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Enkel',
            ],
            [
                'external_id'   => '1046',
                'productnaam'   => 'CT Elleboog exclusief CM',
                'omschrijving'  => 'CT scan van de elleboog',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Elleboog',
            ],
            [
                'external_id'   => '1047',
                'productnaam'   => 'CT Elleboog inclusief CM',
                'omschrijving'  => 'CT scan van de elleboog, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Elleboog',
            ],
            [
                'external_id'   => '1048',
                'productnaam'   => 'CT Hand exclusief CM',
                'omschrijving'  => 'CT scan van de hand',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Hand',
            ],
            [
                'external_id'   => '1049',
                'productnaam'   => 'CT Hand inclusief CM',
                'omschrijving'  => 'CT scan van de hand, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Hand',
            ],
            [
                'external_id'   => '1050',
                'productnaam'   => 'MRI Longen inclusief CM',
                'omschrijving'  => 'MRI scan van de longen, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '281,00',
                'verkoopprijs'  => '750,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Longen',
            ],
            [
                'external_id'   => '1051',
                'productnaam'   => 'CT Longen exclusief CM',
                'omschrijving'  => 'CT scan van de longen',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '450,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Longen',
            ],
            [
                'external_id'   => '1052',
                'productnaam'   => 'CT Longen inclusief CM',
                'omschrijving'  => 'CT scan van de longen, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Longen',
            ],
            [
                'external_id'   => '1053',
                'productnaam'   => 'CTA Longen',
                'omschrijving'  => 'CTA scan van de longen',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '750,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Longen',
            ],
            [
                'external_id'   => '1054',
                'productnaam'   => 'MRI Hart exclusief CM',
                'omschrijving'  => 'MRI scan van het hart',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '750,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Hart',
            ],
            [
                'external_id'   => '1055',
                'productnaam'   => 'MRI Hart inclusief CM',
                'omschrijving'  => 'MRI scan van het hart, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '640,00',
                'verkoopprijs'  => '1350,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Hart',
            ],
            [
                'external_id'   => '1056',
                'productnaam'   => 'Stress MRI Hart inclusief CM',
                'omschrijving'  => 'MRI scan van het hart tijdens kunstmatig opgewekte inspanning',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '697,00',
                'verkoopprijs'  => '1450,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Hart',
            ],
            [
                'external_id'   => '1057',
                'productnaam'   => 'CT Hart exclusief CM (CTC)',
                'omschrijving'  => 'CT scan van het hart (coronaire calciumscore)',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '450,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Hart',
            ],
            [
                'external_id'   => '1058',
                'productnaam'   => 'CT Hart inclusief CM (CTA)',
                'omschrijving'  => 'CT scan van het hart, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '281,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Hart',
            ],
            [
                'external_id'   => '1059',
                'productnaam'   => 'MRI Gehele wervelkolom exclusief CM',
                'omschrijving'  => 'MRI scan van de gehele wervelkolom',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '197,00',
                'verkoopprijs'  => '850,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Gehele wervelkolom',
            ],
            [
                'external_id'   => '1060',
                'productnaam'   => 'MRI Gehele wervelkolom inclusief CM',
                'omschrijving'  => 'MRI scan van de gehele wervelkolom, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '281,00',
                'verkoopprijs'  => '950,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Gehele wervelkolom',
            ],
            [
                'external_id'   => '1061',
                'productnaam'   => 'MRI Halswervelkolom (HWS) exclusief CM',
                'omschrijving'  => 'MRI scan van de halswervelkolom',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Halswervelkolom (HWS)',
            ],
            [
                'external_id'   => '1062',
                'productnaam'   => 'MRI Halswervelkolom (HWS) inclusief CM',
                'omschrijving'  => 'MRI scan van de halswervelkolom, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Halswervelkolom (HWS)',
            ],
            [
                'external_id'   => '1063',
                'productnaam'   => 'MRI Borstwervelkolom (BWS) exclusief CM',
                'omschrijving'  => 'MRI scan van de borstwervelkolom',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Borstwervelkolom (BWS)',
            ],
            [
                'external_id'   => '1064',
                'productnaam'   => 'MRI Borstwervelkolom (BWS) inclusief CM',
                'omschrijving'  => 'MRI scan van de borstwervelkolom, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Borstwervelkolom (BWS)',
            ],
            [
                'external_id'   => '1065',
                'productnaam'   => 'MRI Lendenwervelkolom (LWS) exclusief CM',
                'omschrijving'  => 'MRI scan van de lendenwervelkolom',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Lendenwervelkolom (LWS)',
            ],
            [
                'external_id'   => '1066',
                'productnaam'   => 'MRI Lendenwervelkolom (LWS) inclusief CM',
                'omschrijving'  => 'MRI scan van de lendenwervelkolom, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Lendenwervelkolom (LWS)',
            ],
            [
                'external_id'   => '1067',
                'productnaam'   => 'MRI SI Gewricht inclusief CM',
                'omschrijving'  => 'MRI SI Gewricht inclusief CM',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'SI gewricht',
            ],
            [
                'external_id'   => '1068',
                'productnaam'   => 'MRI SI Gewricht exclusief CM',
                'omschrijving'  => 'MRI SI Gewricht exclusief CM',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'SI gewricht',
            ],
            [
                'external_id'   => '1069',
                'productnaam'   => 'CT Gehele wervelkolom exclusief CM',
                'omschrijving'  => 'CT scan van de gehele wervelkolom',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '850,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Gehele wervelkolom',
            ],
            [
                'external_id'   => '1070',
                'productnaam'   => 'CT Gehele wervelkolom inclusief CM',
                'omschrijving'  => 'CT scan van de gehele wervelkolom, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '281,00',
                'verkoopprijs'  => '950,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Gehele wervelkolom',
            ],
            [
                'external_id'   => '1071',
                'productnaam'   => 'CT Halswervelkolom (HWS) exclusief CM',
                'omschrijving'  => 'CT scan van de halswervelkolom',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Halswervelkolom (HWS)',
            ],
            [
                'external_id'   => '1072',
                'productnaam'   => 'CT Halswervelkolom (HWS) inclusief CM',
                'omschrijving'  => 'CT scan van de halswervelkolom, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Halswervelkolom (HWS)',
            ],
            [
                'external_id'   => '1073',
                'productnaam'   => 'CT Borstwervelkolom (BWS) exclusief CM',
                'omschrijving'  => 'CT scan van de borstwervelkolom',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Borstwervelkolom (BWS)',
            ],
            [
                'external_id'   => '1074',
                'productnaam'   => 'CT Borstwervelkolom (BWS) inclusief CM',
                'omschrijving'  => 'CT scan van de borstwervelkolom, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Borstwervelkolom (BWS)',
            ],
            [
                'external_id'   => '1075',
                'productnaam'   => 'CT Lendenwervelkolom (LWS) exclusief CM',
                'omschrijving'  => 'CT scan van de lendenwervelkolom',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Lendenwervelkolom (LWS)',
            ],
            [
                'external_id'   => '1076',
                'productnaam'   => 'CT Lendenwervelkolom (LWS) inclusief CM',
                'omschrijving'  => 'CT scan van de lendenwervelkolom, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Lendenwervelkolom (LWS)',
            ],
            [
                'external_id'   => '1077',
                'productnaam'   => 'MRI Abdomen exclusief CM',
                'omschrijving'  => 'MRI scan van de onder- en bovenbuik (abdomen), exclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '850,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Abdomen (onderbuik en bovenbuik)',
            ],
            [
                'external_id'   => '1078',
                'productnaam'   => 'MRI Abdomen inclusief CM',
                'omschrijving'  => 'MRI scan van de onder- en bovenbuik (abdomen), inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '850,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Abdomen (onderbuik en bovenbuik)',
            ],
            [
                'external_id'   => '1079',
                'productnaam'   => 'MRI MRCP sequenties',
                'omschrijving'  => 'MRI MRCP sequenties (galwegen)',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '225,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Extra sequenties',
            ],
            [
                'external_id'   => '1080',
                'productnaam'   => 'MRI Bovenbuik inclusief CM',
                'omschrijving'  => 'MRI scan van de bovenbuik, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Bovenbuik',
            ],
            [
                'external_id'   => '1081',
                'productnaam'   => 'MRI Bovenbuik exclusief CM',
                'omschrijving'  => 'MRI scan van de bovenbuik',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Bovenbuik',
            ],
            [
                'external_id'   => '1082',
                'productnaam'   => 'MRI Onderbuik inclusief CM',
                'omschrijving'  => 'MRI scan van de onderbuik, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Onderbuik',
            ],
            [
                'external_id'   => '1083',
                'productnaam'   => 'MRI Onderbuik exclusief CM',
                'omschrijving'  => 'MRI scan van de onderbuik',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Onderbuik',
            ],
            [
                'external_id'   => '1084',
                'productnaam'   => 'CT Abdomen exclusief CM',
                'omschrijving'  => 'CT scan van de onder- en bovenbuik (abdomen)',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '850,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Abdomen (onderbuik en bovenbuik)',
            ],
            [
                'external_id'   => '1085',
                'productnaam'   => 'CT Abdomen inclusief CM',
                'omschrijving'  => 'CT scan van de onder- en bovenbuik (abdomen), inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '850,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Abdomen (onderbuik en bovenbuik)',
            ],
            [
                'external_id'   => '1086',
                'productnaam'   => 'CT Abdomen en buikaorta inclusief CM',
                'omschrijving'  => 'CT scan van de abdomen en buikaorta, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '750,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Abdomen en buikaorta',
            ],
            [
                'external_id'   => '1087',
                'productnaam'   => 'CT Bovenbuik exclusief CM',
                'omschrijving'  => 'CT scan van de bovenbuik',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Bovenbuik',
            ],
            [
                'external_id'   => '1088',
                'productnaam'   => 'CT Bovenbuik inclusief CM',
                'omschrijving'  => 'CT scan van de bovenbuik, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Bovenbuik',
            ],
            [
                'external_id'   => '1089',
                'productnaam'   => 'CT Onderbuik exclusief CM',
                'omschrijving'  => 'CT scan van de onderbuik',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '112,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Onderbuik',
            ],
            [
                'external_id'   => '1090',
                'productnaam'   => 'CT Onderbuik inclusief CM',
                'omschrijving'  => 'CT scan van de onderbuik, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '224,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT scanner',
                'productgroep'  => 'Onderbuik',
            ],
            [
                'external_id'   => '1091',
                'productnaam'   => 'MRI Mammografie inclusief CM',
                'omschrijving'  => 'MRI scan mammografie (borstonderzoek), inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '337,00',
                'verkoopprijs'  => '850,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Borsten',
            ],
            [
                'external_id'   => '1092',
                'productnaam'   => 'MRI Prostaat gedetailleerd inclusief CM',
                'omschrijving'  => 'Gedetailleerde MRI scan van de prostaat, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '337,00',
                'verkoopprijs'  => '950,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Prostaat',
            ],
            [
                'external_id'   => '1093',
                'productnaam'   => 'TB1 Last-Minute Bodyscan',
                'omschrijving'  => 'TB1 Last-Minute Bodyscan, bestaande uit:',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '337,00',
                'verkoopprijs'  => '1250,00',
                'producttype'   => '01 Total Bodyscan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Last-Minute',
            ],
            [
                'external_id'   => '1094',
                'productnaam'   => 'TB1 Royal Bodyscan',
                'omschrijving'  => 'TB1 Royal Bodyscan, bestaande uit:',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '337,00',
                'verkoopprijs'  => '1840,00',
                'producttype'   => '01 Total Bodyscan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Royal',
            ],
            [
                'external_id'   => '1095',
                'productnaam'   => 'TB2 Royal Bodyscan + Angiografie',
                'omschrijving'  => 'TB2 Royal Bodyscan + Angiografie, bestaande uit:',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '506,00',
                'verkoopprijs'  => '2490,00',
                'producttype'   => '01 Total Bodyscan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Royal',
            ],
            [
                'external_id'   => '1096',
                'productnaam'   => 'TB3 Royal Bodyscan + Wervelkolom',
                'omschrijving'  => 'TB3 Royal Bodyscan + Wervelkolom, bestaande uit:',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '506,00',
                'verkoopprijs'  => '2390,00',
                'producttype'   => '01 Total Bodyscan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Royal',
            ],
            [
                'external_id'   => '1097',
                'productnaam'   => 'TB4 Royal Bodyscan + Angiografie + Wervelkolom',
                'omschrijving'  => 'TB4 Royal Bodyscan + Angiografie + Wervelkolom, bestaande uit:',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '618,00',
                'verkoopprijs'  => '3040,00',
                'producttype'   => '01 Total Bodyscan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Royal',
            ],
            [
                'external_id'   => '1098',
                'productnaam'   => 'TB1 Regular Bodyscan zonder cardio',
                'omschrijving'  => 'TB1 Regular Bodyscan zonder cardio, bestaande uit:',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '337,00',
                'verkoopprijs'  => '1340,00',
                'producttype'   => '01 Total Bodyscan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Regular',
            ],
            [
                'external_id'   => '1099',
                'productnaam'   => 'TB2 Regular Bodyscan + Angiografie zonder cardio',
                'omschrijving'  => 'TB2 Regular Bodyscan + Angiografie zonder cardio, bestaande uit:',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '506,00',
                'verkoopprijs'  => '1990,00',
                'producttype'   => '01 Total Bodyscan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Regular',
            ],
            [
                'external_id'   => '1100',
                'productnaam'   => 'TB3 Regular Bodyscan + Wervelkolom zonder cardio',
                'omschrijving'  => 'TB3 Regular Bodyscan + Wervelkolom zonder cardio, bestaande uit:',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '506,00',
                'verkoopprijs'  => '1890,00',
                'producttype'   => '01 Total Bodyscan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Regular',
            ],
            [
                'external_id'   => '1101',
                'productnaam'   => 'TB4 Regular Bodyscan + Angiografie + Wervelkolom zonder cardio',
                'omschrijving'  => 'TB4 Regular Bodyscan + Angiografie + Wervelkolom zonder cardio, bestaande uit:',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '618,00',
                'verkoopprijs'  => '2540,00',
                'producttype'   => '01 Total Bodyscan',
                'resourcetype'  => 'MRI scanner',
                'productgroep'  => 'Regular',
            ],
            [
                'external_id'   => '1102',
                'productnaam'   => 'Bloed- en urineonderzoek preventief uitgebreid dames',
                'omschrijving'  => 'Uitgebreid laboratoriumonderzoek (bloed en urine)',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '45,48',
                'verkoopprijs'  => '250,00',
                'producttype'   => '07 Laboratorium',
                'resourcetype'  => 'Cardiologie',
                'productgroep'  => 'Preventief bloed- en urineonderzoek uitgebreid',
            ],
            [
                'external_id'   => '1103',
                'productnaam'   => 'Bloed- en urineonderzoek preventief uitgebreid heren',
                'omschrijving'  => 'Uitgebreid laboratoriumonderzoek (bloed en urine) met PSA bepaling',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '45,48',
                'verkoopprijs'  => '250,00',
                'producttype'   => '07 Laboratorium',
                'resourcetype'  => 'Cardiologie',
                'productgroep'  => 'Preventief bloed- en urineonderzoek uitgebreid',
            ],
            [
                'external_id'   => '1104',
                'productnaam'   => 'ECG Rust',
                'omschrijving'  => 'Elektrocardiogram (ECG) tijdens rust',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '23,61',
                'verkoopprijs'  => '75,00',
                'producttype'   => '04 Cardiologie',
                'resourcetype'  => 'Cardiologie',
                'productgroep'  => 'Hart Cardio',
            ],
            [
                'external_id'   => '1105',
                'productnaam'   => 'ECG Inspanning',
                'omschrijving'  => 'Elektrocardiogram (ECG) tijdens inspanning',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '24,94',
                'verkoopprijs'  => '75,00',
                'producttype'   => '04 Cardiologie',
                'resourcetype'  => 'Cardiologie',
                'productgroep'  => 'Hart Cardio',
            ],
            [
                'external_id'   => '1106',
                'productnaam'   => 'Echocardiografie Hart',
                'omschrijving'  => 'Echocardiografie van het hart',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '154,46',
                'verkoopprijs'  => '350,00',
                'producttype'   => '04 Cardiologie',
                'resourcetype'  => 'Cardiologie',
                'productgroep'  => 'Hart Cardio',
            ],
            [
                'external_id'   => '1107',
                'productnaam'   => 'Cardiologieprogramma',
                'omschrijving'  => 'Cardiologieprogramma',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '310,31',
                'verkoopprijs'  => '0,00',
                'producttype'   => '04 Cardiologie',
                'resourcetype'  => 'Cardiologie',
                'productgroep'  => 'Hart Cardio',
            ],
            [
                'external_id'   => '1108',
                'productnaam'   => 'Longfunctietest',
                'omschrijving'  => 'Longfunctietest',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '8,16',
                'verkoopprijs'  => '50,00',
                'producttype'   => '04 Cardiologie',
                'resourcetype'  => 'Cardiologie',
                'productgroep'  => 'Longen Cardio',
            ],
            [
                'external_id'   => '1109',
                'productnaam'   => 'PET CT metastasen onderzoek',
                'omschrijving'  => 'PET CT scan van het bovenlichaam, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '1800,00',
                'verkoopprijs'  => '4100,00',
                'producttype'   => '06 PET scan',
                'resourcetype'  => 'PET CT scanner',
                'productgroep'  => 'Metastasen',
            ],
            [
                'external_id'   => '1110',
                'productnaam'   => 'PSMA PET Scan',
                'omschrijving'  => 'PSMA PET scan van het bovenlichaam, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '2400,00',
                'verkoopprijs'  => '4800,00',
                'producttype'   => '06 PET scan',
                'resourcetype'  => 'PET CT scanner',
                'productgroep'  => 'Metastasen',
            ],
            [
                'external_id'   => '1111',
                'productnaam'   => 'Scintigrafie schildklier',
                'omschrijving'  => 'Scintigrafie van de schildklier',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '250,00',
                'verkoopprijs'  => '750,00',
                'producttype'   => '11 Overige',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Schildklier',
            ],
            [
                'external_id'   => '1112',
                'productnaam'   => 'Echo Halsslagaderen',
                'omschrijving'  => 'Echo onderzoek van de halsslagaderen (carotiden)',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '150,00',
                'verkoopprijs'  => '350,00',
                'producttype'   => '11 Overige',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Carotiden',
            ],
            [
                'external_id'   => '1113',
                'productnaam'   => 'Rontgenfoto',
                'omschrijving'  => 'Rontgenfoto',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '44,00',
                'verkoopprijs'  => '250,00',
                'producttype'   => '11 Overige',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Deelonderzoek',
            ],
            [
                'external_id'   => '1114',
                'productnaam'   => 'Volledige vertaling gerichte scan groot',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '60,00',
                'verkoopprijs'  => '110,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Volledige vertaling gericht onderzoek',
            ],
            [
                'external_id'   => '1115',
                'productnaam'   => 'Volledige vertaling gerichte scan klein',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '50,00',
                'verkoopprijs'  => '100,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Volledige vertaling gericht onderzoek',
            ],
            [
                'external_id'   => '1116',
                'productnaam'   => 'Volledige vertaling TB1 zonder cardio',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '150,00',
                'verkoopprijs'  => '80,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Volledige vertaling Total Bodyscan',
            ],
            [
                'external_id'   => '1117',
                'productnaam'   => 'Volledige vertaling TB2 zonder cardio',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '90,00',
                'verkoopprijs'  => '165,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Volledige vertaling Total Bodyscan',
            ],
            [
                'external_id'   => '1118',
                'productnaam'   => 'Volledige vertaling TB3 zonder cardio',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '90,00',
                'verkoopprijs'  => '165,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Volledige vertaling Total Bodyscan',
            ],
            [
                'external_id'   => '1119',
                'productnaam'   => 'Volledige vertaling TB4 zonder cardio',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '105,00',
                'verkoopprijs'  => '185,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Volledige vertaling Total Bodyscan',
            ],
            [
                'external_id'   => '1120',
                'productnaam'   => 'Volledige vertaling TB1',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '125,00',
                'verkoopprijs'  => '215,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Volledige vertaling Total Bodyscan',
            ],
            [
                'external_id'   => '1121',
                'productnaam'   => 'Volledige vertaling TB2',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '125,00',
                'verkoopprijs'  => '215,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Volledige vertaling Total Bodyscan',
            ],
            [
                'external_id'   => '1122',
                'productnaam'   => 'Volledige vertaling TB3',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '125,00',
                'verkoopprijs'  => '215,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Volledige vertaling Total Bodyscan',
            ],
            [
                'external_id'   => '1123',
                'productnaam'   => 'Volledige vertaling TB4',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '140,00',
                'verkoopprijs'  => '240,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Volledige vertaling Total Bodyscan',
            ],
            [
                'external_id'   => '1124',
                'productnaam'   => 'Volledige vertaling TB5',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '125,00',
                'verkoopprijs'  => '215,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Volledige vertaling Total Bodyscan',
            ],
            [
                'external_id'   => '1125',
                'productnaam'   => 'Volledige vertaling aanvullende scan bij TB',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '15,00',
                'verkoopprijs'  => '15,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Volledige vertaling Total Bodyscan',
            ],
            [
                'external_id'   => '1126',
                'productnaam'   => 'Volledige vertaling Herniapoli',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '50,00',
                'verkoopprijs'  => '100,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Volledige vertaling Total Bodyscan',
            ],
            [
                'external_id'   => '1127',
                'productnaam'   => 'Kliniek overnachting',
                'omschrijving'  => 'Overnachting kliniek, per kamer.',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '150,00',
                'verkoopprijs'  => '195,00',
                'producttype'   => '10 Diensten',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Overnachting',
            ],
            [
                'external_id'   => '1128',
                'productnaam'   => 'Aan te passen product (eenmalig)',
                'omschrijving'  => 'Dit dien je elke keer aan te passen',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '0,00',
                'verkoopprijs'  => '0,00',
                'producttype'   => '11 Overige',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Overig',
            ],
            [
                'external_id'   => '1129',
                'productnaam'   => 'Coördinatie- en bemiddelingskosten',
                'omschrijving'  => 'Coördinatie- en bemiddelingskosten',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '0,00',
                'verkoopprijs'  => '59,00',
                'producttype'   => '10 Diensten',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Administratief',
            ],
            [
                'external_id'   => '1130',
                'productnaam'   => 'Toeslag',
                'omschrijving'  => 'Toeslag',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '0,00',
                'verkoopprijs'  => '1,00',
                'producttype'   => '10 Diensten',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Administratief',
            ],
            [
                'external_id'   => '1131',
                'productnaam'   => 'Annulatiekosten',
                'omschrijving'  => 'Annulatiekosten',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '0,00',
                'verkoopprijs'  => '1,00',
                'producttype'   => '10 Diensten',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Administratief',
            ],
            [
                'external_id'   => '1132',
                'productnaam'   => 'Korting',
                'omschrijving'  => 'Korting',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '0,00',
                'verkoopprijs'  => '1,00',
                'producttype'   => '10 Diensten',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Administratief',
            ],
            [
                'external_id'   => '1133',
                'productnaam'   => 'Extra CD',
                'omschrijving'  => 'Extra CD',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '0,00',
                'verkoopprijs'  => '25,00',
                'producttype'   => '10 Diensten',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Administratief',
            ],
            [
                'external_id'   => '1134',
                'productnaam'   => 'Beoordeling Neurochirurg',
                'omschrijving'  => 'PTED - beoordeling MRI / CT beelden van scan',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '0,00',
                'verkoopprijs'  => '100,00',
                'producttype'   => '10 Diensten',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Beoordeling',
            ],
            [
                'external_id'   => '1135',
                'productnaam'   => 'Arts consultatie',
                'omschrijving'  => 'Consultatie Arts',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '0,00',
                'verkoopprijs'  => '350,00',
                'producttype'   => '10 Diensten',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Arts consultatie',
            ],
            [
                'external_id'   => '1136',
                'productnaam'   => 'PTED - operatie 1 niveau',
                'omschrijving'  => 'Transforaminale endoscopische operatie 1 niveau',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '4100,00',
                'verkoopprijs'  => '7900,00',
                'producttype'   => '12 Operaties',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'PTED',
            ],
            [
                'external_id'   => '1137',
                'productnaam'   => 'PTED - operatie 2 niveaus',
                'omschrijving'  => 'Transforaminale endoscopische operatie 2 niveaus',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '5000,00',
                'verkoopprijs'  => '13900,00',
                'producttype'   => '12 Operaties',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'PTED',
            ],
            [
                'external_id'   => '1138',
                'productnaam'   => 'Microscopische operatie 1 niveau',
                'omschrijving'  => 'Microscopische operatie 1 niveau',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '4800,00',
                'verkoopprijs'  => '8900,00',
                'producttype'   => '12 Operaties',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'Micro',
            ],
            [
                'external_id'   => '1139',
                'productnaam'   => 'Microscopische operatie 2 niveaus',
                'omschrijving'  => 'Microscopische operatie 2 niveaus',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '5000,00',
                'verkoopprijs'  => '13900,00',
                'producttype'   => '12 Operaties',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'Micro',
            ],
            [
                'external_id'   => '1140',
                'productnaam'   => 'Microscopische operatie 3 niveaus',
                'omschrijving'  => 'Microscopische operatie 3 niveaus',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '7500,00',
                'verkoopprijs'  => '16900,00',
                'producttype'   => '12 Operaties',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'Micro',
            ],
            [
                'external_id'   => '1141',
                'productnaam'   => 'Microscopische operatie 4 niveaus',
                'omschrijving'  => 'Microscopische operatie 4 niveaus',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '7500,00',
                'verkoopprijs'  => '17900,00',
                'producttype'   => '12 Operaties',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'Micro',
            ],
            [
                'external_id'   => '1142',
                'productnaam'   => 'TLIF 1 niveau',
                'omschrijving'  => 'TLIF operatie 1 niveau',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '9400,00',
                'verkoopprijs'  => '18900,00',
                'producttype'   => '12 Operaties',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'TLIF',
            ],
            [
                'external_id'   => '1143',
                'productnaam'   => 'TLIF 2 niveaus',
                'omschrijving'  => 'TLIF operatie 2 niveaus',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '10800,00',
                'verkoopprijs'  => '18500,00',
                'producttype'   => '12 Operaties',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'TLIF',
            ],
            [
                'external_id'   => '1144',
                'productnaam'   => 'TLIF 3 niveaus',
                'omschrijving'  => 'TLIF operatie 3 niveaus',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '13500,00',
                'verkoopprijs'  => '21500,00',
                'producttype'   => '12 Operaties',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'TLIF',
            ],
            [
                'external_id'   => '1145',
                'productnaam'   => 'ACDF 1 niveau',
                'omschrijving'  => 'ACDF (Anterior Cervical Discectomy and Fusion) operatie 1 niveau',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '4800,00',
                'verkoopprijs'  => '8900,00',
                'producttype'   => '12 Operaties',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'ACDF',
            ],
            [
                'external_id'   => '1146',
                'productnaam'   => 'ACDF 2 niveaus',
                'omschrijving'  => 'ACDF (Anterior Cervical Discectomy and Fusion) operatie 2 niveaus',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '5900,00',
                'verkoopprijs'  => '13900,00',
                'producttype'   => '12 Operaties',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'ACDF',
            ],
            [
                'external_id'   => '1147',
                'productnaam'   => 'Facetinfiltratie 1 niveau',
                'omschrijving'  => 'Facetinfiltratie 1 niveau',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '90,00',
                'verkoopprijs'  => '270,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'Infiltratie',
            ],
            [
                'external_id'   => '1148',
                'productnaam'   => 'Facetinfiltratie 2 niveaus',
                'omschrijving'  => 'Facetinfiltratie 2 niveaus',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '90,00',
                'verkoopprijs'  => '325,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'Infiltratie',
            ],
            [
                'external_id'   => '1149',
                'productnaam'   => 'Facetinfiltratie 3 niveaus',
                'omschrijving'  => 'Facetinfiltratie 3 niveaus',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '90,00',
                'verkoopprijs'  => '350,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'Infiltratie',
            ],
            [
                'external_id'   => '1150',
                'productnaam'   => 'SI-gewricht infiltratie',
                'omschrijving'  => 'SI-gewricht infiltratie (één of beide zijden)',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '90,00',
                'verkoopprijs'  => '270,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'Infiltratie',
            ],
            [
                'external_id'   => '1151',
                'productnaam'   => '1x PRT-injectie',
                'omschrijving'  => '1x PRT-injectie',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '90,00',
                'verkoopprijs'  => '270,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'PRT',
            ],
            [
                'external_id'   => '1152',
                'productnaam'   => '2x PRT-injecties',
                'omschrijving'  => '2x PRT-injecties',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '90,00',
                'verkoopprijs'  => '325,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'PRT',
            ],
            [
                'external_id'   => '1153',
                'productnaam'   => 'Facetdenervatie 1 niveau',
                'omschrijving'  => 'Facetdenervatie 1 niveau',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '500,00',
                'verkoopprijs'  => '890,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'Denervatie',
            ],
            [
                'external_id'   => '1154',
                'productnaam'   => 'Facetdenervatie 2 niveaus',
                'omschrijving'  => 'Facetdenervatie 2 niveaus',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '500,00',
                'verkoopprijs'  => '900,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'Denervatie',
            ],
            [
                'external_id'   => '1155',
                'productnaam'   => 'Facetdenervatie 3 niveaus',
                'omschrijving'  => 'Facetdenervatie 3 niveaus',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '500,00',
                'verkoopprijs'  => '890,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'Artsen',
                'productgroep'  => 'Denervatie',
            ],
            [
                'external_id'   => '1156',
                'productnaam'   => 'TB2 Last-Minute Bodyscan + Angiografie',
                'omschrijving'  => 'TB2 Last-Minute Bodyscan + Angiografie, bestaande uit:',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '506,00',
                'verkoopprijs'  => '1190,00',
                'producttype'   => '01 Total Bodyscan',
                'resourcetype'  => 'MRI Scanner',
                'productgroep'  => 'Last-Minute',
            ],
            [
                'external_id'   => '1157',
                'productnaam'   => 'MRI Abdomen en buikaorta inclusief CM',
                'omschrijving'  => 'MRI scan van de abdomen en buikaorta, inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '350,00',
                'verkoopprijs'  => '850,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI Scanner',
                'productgroep'  => 'Abdomen en buikaorta',
            ],
            [
                'external_id'   => '1158',
                'productnaam'   => 'Vertaalde samenvatting aanvullende scan bij TB',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '5,00',
                'verkoopprijs'  => '20,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Vertaalde samenvatting',
            ],
            [
                'external_id'   => '1159',
                'productnaam'   => 'Volledige vertaling Gastroscopie',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '22,50',
                'verkoopprijs'  => '45,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Volledige vertaling gericht onderzoek',
            ],
            [
                'external_id'   => '1160',
                'productnaam'   => 'Volledige vertaling Coloscopie',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '22,50',
                'verkoopprijs'  => '45,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Volledige vertaling gericht onderzoek',
            ],
            [
                'external_id'   => '1161',
                'productnaam'   => 'Volledige vertaling Gastroscopie en Coloscopie',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '40,00',
                'verkoopprijs'  => '90,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Volledige vertaling gericht onderzoek',
            ],
            [
                'external_id'   => '1162',
                'productnaam'   => 'Volledige vertaling TB0',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '40,00',
                'verkoopprijs'  => '80,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Volledige vertaling Total bodyscan',
            ],
            [
                'external_id'   => '1163',
                'productnaam'   => 'Vertaalde samenvatting TBx',
                'omschrijving'  => 'Nederlandse vertaling van de rapportage',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '35,00',
                'verkoopprijs'  => '90,00',
                'producttype'   => '09 Vertaling',
                'resourcetype'  => 'Other',
                'productgroep'  => 'Vertaalde samenvatting',
            ],
            [
                'external_id'   => '1164',
                'productnaam'   => 'MRI Halswervel- en borstwervelkolom (HWS-BWS) excl',
                'omschrijving'  => 'MRI scan van de halswervel- en borstwervelkolom',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '165,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI Scanner',
                'productgroep'  => 'Halswervel- en borstwervelkolom (HWS-BWS)',
            ],
            [
                'external_id'   => '1165',
                'productnaam'   => 'CT Hart en longen (Thorax) exclusief CM',
                'omschrijving'  => 'CT scan van het hart en de longen (thorax), exclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '169,00',
                'verkoopprijs'  => '650,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT Scanner',
                'productgroep'  => 'Hart en longen (Thorax)',
            ],
            [
                'external_id'   => '1166',
                'productnaam'   => 'CT Hart en longen (Thorax) inclusief CM',
                'omschrijving'  => 'CT scan van het hart en de longen (thorax), inclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '250,00',
                'verkoopprijs'  => '550,00',
                'producttype'   => '03 CT scan',
                'resourcetype'  => 'CT Scanner',
                'productgroep'  => 'Hart en longen (Thorax)',
            ],
            [
                'external_id'   => '1167',
                'productnaam'   => 'MRI Hydro Coloscopie inclusief CM',
                'omschrijving'  => 'MRI scan van de darmen (Hydro coloscopie)',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '350,00',
                'verkoopprijs'  => '850,00',
                'producttype'   => '02 MRI scan',
                'resourcetype'  => 'MRI Scanner',
                'productgroep'  => 'Abdomen en buikaorta',
            ],
            [
                'external_id'   => '1168',
                'productnaam'   => 'MRI hele lichaam exclusief CM',
                'omschrijving'  => 'MRI van het hele lichaam, exclusief contrastmiddel',
                'valuta'        => 'EUR',
                'inkoopprijs'   => '550,00',
                'verkoopprijs'  => '1900,00',
                'producttype'   => '01 Total Bodyscan',
                'resourcetype'  => 'MRI Scanner',
                'productgroep'  => 'Bodyscans',
            ],
        ];

        foreach ($rows as $row) {
            $name = $row['productnaam'];

            // Resolve ProductType by name (label) if provided
            $productTypeId = null;
            if (! empty($row['producttype'])) {
                $productTypeId = $this->mapProductTypeNameToId($row['producttype']);
            }

            // Resolve ResourceType by display name via enum mapping
            $resourceType = $this->mapResourceTypeNameToModel($row['resourcetype']);

            // Resolve ProductGroup by name
            $group = ProductGroup::where('name', $row['productgroep'])->first();
            if (! $group) {
                throw new RuntimeException("ProductGroup not found: {$row['productgroep']}");
            }

            $price = Currency::normalizePrice($row['verkoopprijs'] ?? null) ?? '0.00';
            $costs = Currency::normalizePrice($row['inkoopprijs'] ?? null) ?? '0.00';
            $currency = $row['valuta'] ?? 'EUR';
            $externalId = $row['external_id'] ?? null;

            Product::create([
                'name'             => $name,
                'external_id'      => $externalId,
                'description'      => $row['omschrijving'] ?? null,
                'currency'         => $currency,
                'price'            => $price,
                'costs'            => $costs,
                'resource_type_id' => $resourceType->id,
                'product_type_id'  => $productTypeId,
                'product_group_id' => $group->id,
                'active'           => true,
            ]);
        }
    }

    private function mapProductTypeNameToId(string $name): int
    {
        $ProductTypeEnum = match ($name) {
            '01 Total Bodyscan' => ProductTypeEnum::TOTAL_BODYSCAN,
            '02 MRI scan'       => ProductTypeEnum::MRI_SCAN,
            '03 CT scan'        => ProductTypeEnum::CT_SCAN,
            '04 Cardiologie'    => ProductTypeEnum::CARDIOLOGIE,
            '06 PET scan'       => ProductTypeEnum::PETSCAN,
            '07 Laboratorium'   => ProductTypeEnum::LABORATORIUM,
            '09 Vertaling'      => ProductTypeEnum::VERTALING,
            '10 Diensten'       => ProductTypeEnum::DIENSTEN,
            '11 Overige'        => ProductTypeEnum::OVERIG,
            '12 Operaties'      => ProductTypeEnum::OPERATIONS,
            default             => throw new Exception("Unknown ProductType name: {$name}"),
        };

        $productType = ProductType::where('name', $ProductTypeEnum->label())->first();

        return $productType ? $productType->id : throw new Exception("ProductType not found: {$name}");
    }

    private function mapResourceTypeNameToModel(string $name): ResourceType
    {
        // normalize to lowercase for case-insensitive matching
        $normalized = mb_strtolower(trim($name));

        $resourceTypeEnum = match ($normalized) {
            'mri scanner'    => ResourceTypeEnum::MRI_SCANNER,
            'ct scanner'     => ResourceTypeEnum::CT_SCANNER,
            'pet ct scanner' => ResourceTypeEnum::PET_CT_SCANNER,
            'artsen'         => ResourceTypeEnum::ARTSEN,
            'other', 'overig' => ResourceTypeEnum::OTHER,
            'cardiologie'    => ResourceTypeEnum::CARDIOLOGIE,

            default => throw new Exception("Unknown ResourceType name: {$name}"),
        };

        $resourceType = ResourceType::where('name', $resourceTypeEnum->label())->first();

        return $resourceType ?: throw new RuntimeException("ResourceType not found: {$name}");
    }
}
