server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    root /usr/share/nginx/html/public;

    index index.php index.html;

    # Access logs naar file (niet naar Grafana)
    access_log /var/log/nginx/access.log;
    # Error logs naar stderr (voor Grafana via Promtail)
    error_log /proc/self/fd/2;

    client_max_body_size 100M;

    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}
