FROM php:8.2-cli

# Installeer afhankelijkheden voor PHP-extensies
RUN apt-get update && apt-get install -y \
    unzip \
    git \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zlib1g-dev \
    libicu-dev \
    libxml2-dev \
    libonig-dev \
    libgmp-dev \
    libssl-dev \
    && docker-php-ext-install \
        calendar \
        zip \
        gd \
    && rm -rf /var/lib/apt/lists/*

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /app
COPY . /app

# Install PHP dependencies
RUN composer install
