### create  lead
POST http://localhost:8000/api/leads
Content-Type: application/json

{
    "first_name": "Bart",
    "last_name": "Bulthuis",
    "email": "bart@example.com",
    "phone": "0612345678",
    "company_name": "Woonkamp B.V.",
    "lead_source": "Website",
    "title": "lead tel (hernia)",
    "lead_source_id": 2,
    "tags": ["crm", "n8n"]
}



### create lead (privatescan)
POST https://{{ URL }}/api/leads/privatescan
Accept: application/json
Content-Type: application/json
X-API-KEY: {{API_KEY}}

{
    "lead_source": "architecto",
    "kanaal_c": "architecto",
    "soort_aanvraag_c": "preventie",
    "first_name": "architecto",
    "last_name": "architecto",
    "email": "zbailey@example.net",
    "phone": "architecto",
    "description": "Eius et animi quos velit et.",
    "url": "http://www.ernser.org/harum-mollitia-modi-deserunt-aut-ab-provident-perspiciatis-quo.html",
    "section": "architecto",
    "select_verzoek": "architecto",
    "select_interesse": "architecto",
    "campaign_id": "architecto"
}


### create lead (hernia)
POST https://{{ URL }}/api/leads/hernia
Accept: application/json
Content-Type: application/json
X-API-KEY: {{API_KEY}}

{
    "campaign_id": "architecto",
    "lead_source": "architecto",
    "kanaal_c": "architecto",
    "soort_aanvraag_c": "architecto",
    "salutation": "architecto",
    "first_name": "architecto",
    "last_name": "architecto",
    "birthdate": "2026-01-22",
    "email1": "zbailey@example.net",
    "phone_mobile": "architecto",
    "primary_huisnr_c": "architecto",
    "primary_huisnr_toevoeging_c": "architecto",
    "primary_address_postalcode": "architecto",
    "description": "Eius et animi quos velit et."
}


### create workflow lead
POST http://{{ URL }}/api/sales-leads
Content-Type: application/json

{
    "lead_id": 164
}

### find activities by lead
GET http://{{ URL }}/api/leads/238/activities
Content-Type: application/json


### get lead by id
GET http://{{ URL }}/api/leads/238
Content-Type: application/json

### zoek contact persons
GET http://{{ URL }}/admin/contacts/persons/search
Content-Type: application/json

{
    "first_name": "John"
}

### get person info
GET https://{{ URL }}/api/keycloak/persons/39cdb90c-b41e-4126-b271-daafaa29f982
Accept: application/json
Content-Type: application/json
X-API-KEY: {{API_KEY}}

### get person info
GET https://{{ URL }}/api/patient/4e162dae-4ea9-4b66-ae67-9ff1fb3f57ed/documents
Accept: application/json
Content-Type: application/json
X-API-KEY: {{API_KEY}}

### get person info
GET https://{{ URL }}/api/patient/4e162dae-4ea9-4b66-ae67-9ff1fb3f57ed/notifications
Accept: application/json
Content-Type: application/json
X-API-KEY: {{API_KEY}}
