services:
  #  krayin-php-apache:
  #    build:
  #      args:
  #        container_project_path: /var/www/html/
  #        uid: 1000 # add your uid here
  #        user: $USER
  #      context: .
  #      dockerfile: ./Dockerfile
  #    image: krayin-php-apache
  #    ports:
  #      - 80:80 # adjust your port here, if you want to change
  #    volumes:
  #      - ./workspace/:/var/www/html/

  crm:
    build:
      context: ./vendor/laravel/sail/runtimes/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
        WWWUSER: '${WWWUSER:-1000}'
    image: sail-8.2/app
    container_name: crm
    stdin_open: true
    tty: true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
      - '8000:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-debug}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    env_file:
      - .env
    labels:
      - 'dev.orbstack.domains=${TRAEFIK_URL}'
      - traefik.enable=true
      - traefik.http.routers.laravel-template-api-rtr.rule=Host(`$TRAEFIK_URL`)
      - traefik.http.routers.laravel-template-api-rtr.tls=true
      - traefik.http.routers.laravel-template-api-rtr.entrypoints=https
      - traefik.http.routers.laravel-template-api-rtr.service=laravel-template-api-svc
      - traefik.http.services.laravel-template-api-svc.loadbalancer.server.port=80
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
      - mb_traefik
    depends_on:
      - mysql
  #      - redis

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      #      - '${FORWARD_DB_PORT:-3306}:3306'
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - sail
      - mb_traefik
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  #  krayin-phpmyadmin:
  #    image: phpmyadmin:latest
  #    restart: always
  #    environment:
  #      PMA_HOST: krayin-mysql
  #      PMA_USER: root
  #      PMA_PASSWORD: root
  #    ports:
  #      - 8080:80 # adjust your port here, if you want to change

  #  This n8N will service for production workflows. For data flows, we will set up a separate n8n instance and will run on our data server.
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=sqlite
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=changeme
      - N8N_HOST=n8n.local
      - N8N_PORT=5678
      - TZ=Europe/Amsterdam
    networks:
      - sail
      - mb_traefik
    volumes:
      - n8n_data:/home/node/.n8n
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test-runner
    volumes:
      - .:/app
    depends_on:
      - crm
      - n8n
    command: ./vendor/bin/behat --format=pretty

networks:
  sail:
    driver: bridge
  mb_traefik:
    external: true
volumes:
  sail-mysql:
    driver: local
  n8n_data:
    driver: local

  #  sail-redis:
  #    driver: local






