services:

  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.file.filename=/traefik/tls.yml
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=public
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443/tcp
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
    ports:
      - "80:80"
      - "443:443"
      - "8089:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./.docker/traefik_local:/traefik:ro
    networks:
      public:
        aliases:
          - sso.local.privatescan.nl
          - crm.local.privatescan.nl
          - patient.local.privatescan.nl

  crm:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
        WWWUSER: '${WWWUSER:-1000}'
        APP_ENV: 'local'
    image: sail-8.3/crm
    container_name: crm
    stdin_open: true
    tty: true
    ports:
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
      - '${VITE_ADMIN_PORT:-5174}:${VITE_ADMIN_PORT:-5174}'
      - '8000:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-debug}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.crm.rule=Host("crm.local.privatescan.nl")
      - traefik.http.routers.crm.entrypoints=https
      - traefik.http.routers.crm.tls=true
      - traefik.http.routers.crm.tls.domains[0].main=crm.local.privatescan.nl
      - traefik.http.routers.crm.service=crm-svc
      - traefik.http.services.crm-svc.loadbalancer.server.port=80
      # Middleware: expliciete headers doorgeven
      - traefik.http.middlewares.crm-forward-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.crm-forward-headers.headers.customrequestheaders.X-Forwarded-Port=443
      - traefik.http.middlewares.crm-forward-headers.headers.customrequestheaders.X-Forwarded-Host=crm.local.privatescan.nl
      - traefik.docker.network=public
      - logging=promtail
    volumes:
      - '.:/usr/share/nginx/html'
      - './certs:/certs:ro'
    extra_hosts:
      - "clinicdev.local.privatescan.nl:host-gateway"
      - "patientdev.local.privatescan.nl:host-gateway"
      - "formsdev.local.privatescan.nl:host-gateway"
    networks:
      public:
      backend:
      privateforms_form_traefik:
    depends_on:
      - mysql

  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql_crm
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'crm-mysql:/var/lib/mysql'
      # note: in prod, these are copies by update-and-run.sh
      - './.docker/mysql/init-forms.sql:/docker-entrypoint-initdb.d/21-init-forms.sql'
    networks:
      - backend
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  k6:
    image: grafana/k6:latest
    container_name: k6
    working_dir: /scripts
    volumes:
      - ./k6-scripts:/scripts
    networks:
      - backend
    depends_on:
      - crm

  forms:
    image: ghcr.io/privatescanbv/privateforms/forms:latest
    container_name: forms
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      WWWUSER: '${WWWUSER}'
      WWWGROUP: '${WWWGROUP}'
      APP_NAME: 'PrivateForms'
      APP_ENV: 'production'
      APP_KEY: 'base64:i8u5O+j9QB823zOyqJFjsqr2iINU9Z1cFdr5HTfKNOg='
      API_KEY_1: '4!LvFF3HNTUGz*E^X@kk'
      APP_DEBUG: 'false'
      APP_URL: 'http://forms.local'
      ASSET_URL: 'http://forms.local'
      POSTMARK_TOKEN: '3ea2bc92-4dd0-4bc5-af86-fb764e5d7af9'
      MAIL_FROM_ADDRESS: 'no-reply@privatescan.nl'
      MAIL_FROM_NAME: 'PrivateScan'
      APP_MAINTENANCE_DRIVER: 'file'
      PHP_CLI_SERVER_WORKERS: 4
      BCRYPT_ROUNDS: 12
      LOG_CHANNEL: 'stack'
      LOG_LEVEL: 'debug'
      DB_CONNECTION: 'mysql'
      DB_HOST: 'mysql_crm'
      DB_PORT: '3306'
      DB_DATABASE: 'forms'
      DB_USERNAME: 'formadmin'
      DB_PASSWORD: 'FUC16A-qsh(<d!io'
      APP_TIMEZONE: 'UTC'
      SESSION_DRIVER: 'file'
      SESSION_LIFETIME: 120
      SESSION_DOMAIN: ''
      SESSION_SECURE: 'false'
      SESSION_SAME_SITE: 'lax'
      SESSION_PATH: '/'
      BROADCAST_CONNECTION: 'log'
      FILESYSTEM_DISK: 'local'
      QUEUE_CONNECTION: 'database'
      CACHE_STORE: 'database'
      MEMCACHED_HOST: '127.0.0.1'
      FORWARD_REDIS_PORT: 6379
      VITE_APP_NAME: 'PrivateForms'
      EMAIL_VERIFICATION_BCC: 'mark.bulthuis@privatescan.nl'
      KEYCLOAK_BASE_URL: 'https://sso.local.privatescan.nl'
      KEYCLOAK_REALM: '${KEYCLOAK_REALM}'
      KEYCLOAK_CLIENT_ID: 'patient-app'
      KEYCLOAK_LOAD_USER_FROM_DATABASE: false
      KEYCLOAK_APPEND_DECODED_TOKEN: true
      KEYCLOAK_ALLOWED_RESOURCES: 'patient-app'
      KEYCLOAK_LEEWAY: 60
      KEYCLOAK_CLIENT_SECRET: "$PATIENT_PORTAL_KEYCLOAK_CLIENT_SECRET"
      CRM_API_KEY: "${API_KEY_1}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.laravel-template-api-rtr.rule=Host("forms.local.privatescan.nl")
      - traefik.http.routers.laravel-template-api-rtr.tls=true
      - traefik.http.routers.laravel-template-api-rtr.tls.domains[0].main=forms.local.privatescan.nl
      - traefik.http.routers.laravel-template-api-rtr.entrypoints=https
      - traefik.http.routers.laravel-template-api-rtr.service=laravel-template-api-svc
      - traefik.http.routers.laravel-template-api-rtr.middlewares=forms-forward-headers
      - traefik.http.services.laravel-template-api-svc.loadbalancer.server.port=80
      - traefik.http.middlewares.forms-forward-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.forms-forward-headers.headers.customrequestheaders.X-Forwarded-Port=443
      - traefik.http.middlewares.forms-forward-headers.headers.customrequestheaders.X-Forwarded-Host=forms.local.privatescan.nl
      - traefik.docker.network=public
      - logging=promtail
    networks:
      public:
      backend:
    depends_on:
      crm:
        condition: service_started
      mysql:
        condition: service_healthy

  loki-init:
    image: alpine:latest
    container_name: loki-init
    user: root
    volumes:
      - loki-data:/loki
      - ./docker/loki/init-loki.sh:/init-loki.sh:ro
    command: sh /init-loki.sh
    networks:
      - backend
    restart: "no"

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    user: "10001:10001"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
      - ./.docker/config/loki/loki-config.yml:/etc/loki/local-config.yaml:ro
    networks:
      - backend
    labels:
      - logging=promtail
    depends_on:
      loki-init:
        condition: service_completed_successfully

  promtail:
    image: grafana/promtail:3.5.8
    container_name: promtail
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.docker/config/promtail/promtail-config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - backend
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - public
      - backend
    labels:
      - logging=promtail
    depends_on:
      - loki

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    restart: unless-stopped
    env_file:
      - .env.keycloak
    environment:
      TZ: Europe/Amsterdam
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      # KC_DB_USERNAME, KC_DB_PASSWORD, KC_BOOTSTRAP_ADMIN_USERNAME en KC_BOOTSTRAP_ADMIN_PASSWORD worden automatisch gekopieerd van KEYCLOAK_DB_USERNAME, KEYCLOAK_DB_PASSWORD, KEYCLOAK_ADMIN en KEYCLOAK_ADMIN_PASSWORD via entrypoint
      KC_HOSTNAME: "sso.local.privatescan.nl"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_PROXY: "edge"
      KC_PROXY_ADDRESS_FORWARDING: "true"
    entrypoint: >
      /bin/sh -c "
        export KC_DB_USERNAME=$${KEYCLOAK_DB_USERNAME:-keycloak} &&
        export KC_DB_PASSWORD=$${KEYCLOAK_DB_PASSWORD:-changeme} &&
        export KC_BOOTSTRAP_ADMIN_USERNAME=$${KEYCLOAK_ADMIN} &&
        export KC_BOOTSTRAP_ADMIN_PASSWORD=$${KEYCLOAK_ADMIN_PASSWORD} &&
        exec /opt/keycloak/bin/kc.sh start
      "
    ports:
      - "8085:8080"
      - "8443:8443"
    networks:
      public:
      backend:
    volumes:
      - ./.docker/keycloak/providers:/opt/keycloak/providers
      - ./.docker/keycloak/themes:/opt/keycloak/themes
    depends_on:
      keycloak-db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.rule=Host("sso.local.privatescan.nl")
      - traefik.http.routers.keycloak.entrypoints=https
      - traefik.http.routers.keycloak.tls=true
      - traefik.http.routers.keycloak.tls.domains[0].main=sso.local.privatescan.nl
      - traefik.http.routers.keycloak.service=keycloak-svc
      - traefik.http.services.keycloak-svc.loadbalancer.server.port=8080
      - traefik.http.middlewares.keycloak-forward-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.keycloak-forward-headers.headers.customrequestheaders.X-Forwarded-Port=443
      - traefik.http.middlewares.keycloak-forward-headers.headers.customrequestheaders.X-Forwarded-Host=sso.local.privatescan.nl
      - traefik.http.routers.keycloak.middlewares=keycloak-forward-headers
      - traefik.docker.network=public
      - logging=promtail
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

  keycloak-db:
    image: postgres:15-alpine
    container_name: keycloak-db
    restart: unless-stopped
    env_file:
      - .env.keycloak
    environment:
      POSTGRES_DB: keycloak
      # POSTGRES_USER en POSTGRES_PASSWORD worden automatisch gekopieerd van KEYCLOAK_DB_USERNAME en KEYCLOAK_DB_PASSWORD via entrypoint
    entrypoint: ["/bin/sh", "-c", "export POSTGRES_USER=$${KEYCLOAK_DB_USERNAME:-keycloak} && export POSTGRES_PASSWORD=$${KEYCLOAK_DB_PASSWORD:-changeme} && exec docker-entrypoint.sh postgres"]
    ports:
      - "5432:5432"
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-keycloak}"]
      interval: 10s
      timeout: 5s
      retries: 5


#  ai-agent:
#    build: ./ai-agents/ai-agent
#    container_name: ai-agent
#    env_file:
#      - .env.ai
#    environment:
#      - DB_HOST=mysql
#      - DB_PORT=3306
#      - DB_USER=${DB_USERNAME}
#      - DB_PASS=${DB_PASSWORD}
#      - DB_NAME=${DB_DATABASE}
#    ports:
#      - "8001:8001"
#    depends_on:
#      - mysql
#    networks:
#      - public
#      - backend
#
#  ai-frontend:
#    build: ./ai-agents/ai-frontend
#    container_name: ai-frontend
#    ports:
#      - "8501:8501"
#    depends_on:
#      - ai-agent
#    networks:
#      - backend
#
#  ai-visualizer:
#    build: ./ai-agents/ai-visualizer
#    container_name: ai-visualizer
#    ports:
#      - "8002:8002"
#    env_file:
#      - .env.ai
#    networks:
#      - public
#      - backend


networks:
  backend:
    driver: bridge
  public:
    driver: bridge
  privateforms_form_traefik:
    external: ${USE_EXTERNAL_TRAEFIK_NETWORK:-false}
    name: ${TRAEFIK_NETWORK_NAME:-privateforms_form_traefik}

volumes:
  crm-mysql:
    driver: local
  loki-data:
    driver: local
  grafana-data:
    driver: local
  keycloak-db-data:
    driver: local
