services:

  crm:
    image: ghcr.io/privatescanbv/krayin-laravel-crm/krayincrm:latest
    container_name: crm
    restart: unless-stopped
    stdin_open: true
    tty: true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.forms.rule=Host(`newcrm.dev.privatescan.nl`)
      - traefik.http.routers.forms.entrypoints=https
      - traefik.http.routers.forms.tls=true
      - traefik.http.routers.forms.tls.certresolver=myresolver
      - traefik.http.routers.forms.service=forms-svc
      - traefik.http.services.forms-svc.loadbalancer.server.port=80
      # Protect CRM log viewer path with Basic Auth
      - traefik.http.routers.forms-logviewer.rule=Host(`newcrm.dev.privatescan.nl`) && PathPrefix(`/log-viewer`)
      - traefik.http.routers.forms-logviewer.entrypoints=https
      - traefik.http.routers.forms-logviewer.tls=true
      - traefik.http.routers.forms-logviewer.tls.certresolver=myresolver
      - traefik.http.routers.forms-logviewer.service=forms-svc
      - traefik.http.routers.forms-logviewer.middlewares=crm-logauth,forward-headers
      - traefik.http.middlewares.crm-logauth.basicauth.users=logviewer:$$apr1$$H5jLv78F$$TFMkJ79Ez/XCa2qQDaVkm/
      # Middleware: expliciete headers doorgeven
      - traefik.http.middlewares.forward-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.forward-headers.headers.customrequestheaders.X-Forwarded-Port=443
      - traefik.http.middlewares.forward-headers.headers.customrequestheaders.X-Forwarded-Host=newcrm.dev.privatescan.nl
      - traefik.docker.network=mb_traefik
    volumes:
      - '/home/mbulthuis/upload:/var/www/html/upload_sugarcrm'
    networks:
      - sail
      - mb_traefik
    depends_on:
      - mysql
      - n8n
      - mailserver
    healthcheck:
      test: [
        "CMD-SHELL",
        'curl -f -H "X-N8N-API-KEY: $N8N_API_KEY" http://n8n:5678/webhook/health-check'
      ]
      interval: 30s
      timeout: 5s
      retries: 3

  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql
    ports:
      - '3307:3306'
    command: --skip-host-cache --skip-name-resolve --socket=/tmp/mysql.sock
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
#      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
      - './docker/mysql/init-n8n.sql:/docker-entrypoint-initdb.d/20-init-n8n.sql'
    networks:
      - sail
      - mb_traefik
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-p$DB_PASSWORD"]
#      retries: 3
#      timeout: 5s

  #  This n8N will service for production workflows. For data flows, we will set up a separate n8n instance and will run on our data server.
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
#    ports:
#      - "5678:5678"
    env_file:
      - .env
    environment:
      DB_TYPE: 'mysqldb'
      N8N_BASIC_AUTH_ACTIVE: 'false'
#      N8N_BASIC_AUTH_USER: 'admin'
#      N8N_BASIC_AUTH_PASSWORD: "V!*q3&hD8Lsq8yL3RdAY"
      N8N_API_KEY: '${N8N_API_KEY}'
      N8N_HOST: 'n8n.local'
      N8N_PORT: 5678
      TZ: 'Europe/Amsterdam'
      N8N_ENCRYPTION_KEY: 'FUC16A-23(<d!io'
      N8N_RUN_MIGRATIONS: 'true'
      N8N_RUNNERS_ENABLED: 'true'
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`n8ncrm.dev.privatescan.nl`)
      - traefik.http.routers.n8n.entrypoints=https
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.tls.certresolver=myresolver
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - traefik.docker.network=mb_traefik
    networks:
      - sail
      - mb_traefik
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - mysql

  n8n-sync:
    image: ghcr.io/privatescanbv/krayin-laravel-crm/crmsyncn8n:latest
    container_name: n8n-sync
    env_file:
      - .env
    environment:
      N8N_RUNNERS_ENABLED: 'true'
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
      DB_TYPE: 'mysqldb'
      N8N_HOST: 'n8n'
      N8N_PORT: '5678'
      N8N_API_URL: 'http://n8n:5678/api/v1/workflows'
    depends_on:
      - n8n
    networks:
      - sail

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: '${DB_PASSWORD}'
      UPLOAD_LIMIT: 300M
    labels:
      - traefik.enable=true
      - traefik.http.routers.pma.rule=Host(`phpmyadmin.dev.privatescan.nl`)
      - traefik.http.routers.pma.entrypoints=https
      - traefik.http.routers.pma.tls=true
      - traefik.http.routers.pma.tls.certresolver=myresolver
      - traefik.http.routers.pma.middlewares=pma-auth
      - traefik.http.middlewares.pma-auth.basicauth.users=admin:$$2y$$05$$13501WAPEwnZGYkGbsZ.duBZGb.C9wQYQiAqeIZM8SyAqTuAVd7Xe
      - traefik.http.services.pma.loadbalancer.server.port=80
      - traefik.docker.network=mb_traefik
    networks:
      - sail
      - mb_traefik
    depends_on:
      - mysql

  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.myresolver.acme.email=mark.bulthuis@mbsoftware.nl"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - mb_traefik

  mailserver:
    image: mailserver/docker-mailserver:latest
    hostname: mail
    domainname: test.local
    container_name: mailserver
    env_file: mailserver.env
    environment:
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/docker-mailserver/ssl/mail.test.local-cert.pem
      - SSL_KEY_PATH=/tmp/docker-mailserver/ssl/mail.test.local-key.pem
    volumes:
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./docker/config/:/tmp/docker-mailserver/
    ports:
      - "1025:25"     # SMTP inkomend (van Laravel)
      - "587:587"     # SMTP met AUTH (voor RainLoop)
      - "993:993"     # IMAPS voor Webklex of mailclient
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - sail

  # visueel mailtjes kunnen lezen (local development)
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    ports:
      - "8888:8888"  # Webmail
    restart: unless-stopped
    depends_on:
      - mailserver
    networks:
      - sail
      - mb_traefik
    volumes:
      - './rainloop_data:/rainloop/data'
    labels:
      - traefik.enable=true
      - traefik.http.routers.rainloop.rule=Host(`webmail.dev.privatescan.nl`)
      - traefik.http.routers.rainloop.entrypoints=https
      - traefik.http.routers.rainloop.tls=true
      - traefik.http.routers.rainloop.tls.certresolver=myresolver
      - traefik.http.services.rainloop.loadbalancer.server.port=8888
      - traefik.docker.network=mb_traefik

  suitecrm:
    image: ghcr.io/privatescanbv/privatecrm/suitecrm:1.0
    container_name: suitecrm
    ports:
      - "81:80"
    environment:
      SITE_URL: 'https://suitecrm.dev.privatescan.nl'
    labels:
      - traefik.enable=true
      - traefik.docker.network=mb_traefik
      - traefik.http.routers.suitecrm.rule=Host(`suitecrm.dev.privatescan.nl`)
      - traefik.http.routers.suitecrm.entrypoints=https
      - traefik.http.routers.suitecrm.tls=true
      - traefik.http.routers.suitecrm.tls.certresolver=myresolver
      - traefik.http.routers.suitecrm.service=suitecrm-svc
      - traefik.http.services.suitecrm-svc.loadbalancer.server.port=80
      - traefik.http.middlewares.suitecrm-forward.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.suitecrm-forward.headers.customrequestheaders.X-Forwarded-Port=443
      - traefik.http.middlewares.suitecrm-forward.headers.customrequestheaders.X-Forwarded-Host=suitecrm.dev.privatescan.nl
      - traefik.http.routers.suitecrm.middlewares=suitecrm-forward@docker
    networks:
      - sail
      - mb_traefik
    depends_on:
      - mysql

networks:
  sail:
    driver: bridge
  mb_traefik:
    external: true

volumes:
  sail-mysql:
    driver: local
  n8n_data:
    driver: local
