PrivateScan CRM

=== Introduction

De PrivateScan CRM is ontwikkeld als vervanging van het verouderde SugarCRM-systeem. Door de technische beperkingen en het gebrek aan ontwikkelmogelijkheden in het oude systeem was verdere doorontwikkeling niet meer haalbaar.

Er is daarom bewust gekozen om het nieuwe systeem volledig vanaf de basis op te bouwen. Daarbij zijn waardevolle onderdelen uit SugarCRM hergebruikt waar zinvol, maar is tegelijkertijd gekozen voor een frisse, toekomstbestendige opzet waarmee we weer jaren vooruit kunnen.


=== Opdrachtomschrijving / Businessdoelstellingen

Opdracht komt voort uit advies rapport, zie onze share op de Citrix omgeving;: file:///P:/Healthcare%20Solution/Resultaten%20deelopdrachten/Deelopdracht%202/Adviesdocument%20CRM%20keuze.pdf

=== Doelgroep
De primaire doelgroep bestaat uit medewerkers van Privatescan die betrokken zijn bij het klantcontact, de planning van medische onderzoeken en de administratieve afhandeling. Denk hierbij aan:

* Frontoffice medewerkers – verantwoordelijk voor intake, communicatie met patiënten, en het plannen van afspraken.

* Backoffice personeel – belast met orderverwerking, facturatie en nazorg.

* Medisch coördinatoren – die overzicht houden over dossiers, specialisten en kliniekplanning. (geen toegang tot CRM), zal een los portaal krijgen)

* Patienten - los patient portaal (geen toegang tot CRM)

* Management – dat behoefte heeft aan inzicht in lopende aanvragen, doorlooptijden en conversiepercentages.

De gebruikers zijn overwegend niet technisch en verwachten een intuïtieve interface waarin ze snel overzicht krijgen over hun verantwoordelijkheden. Efficiëntie, foutpreventie en goede logging zijn van groot belang, mede vanwege het medische en privacygevoelige karakter van de dienstverlening.



=== Wie werkt er aan dit project?

Vast team samenstelling bestaat uit het onderstaande schema.
Vaak zetten we er ook een flexibele schil naast, die vaak niet aanwezig zijn met gezamenlijke sessies.

[cols="1,1,1,1"]
|===
|Team Privatescan |Rol(len)| e-mailadres |Telefoonnummer

|Mark klaucke
|Productowner(PO)
|link:mailto:mark.klaucke@digi4you.nl[mark]
|

|Mark Bulthuis
|Architect
|mark.bulthuis@mbsoftware.nl
|0611251149

|===

*Stakeholders*

[cols="1,1,1"]
|===
|Klant |Rol(len)| e-mailadres

|Frank Hefti
|Eigenaar Privatescan B.V.
|link:mailto:frank@privatescan.nl[frank@privatescan.eu]

|Petra Nijhof
| x
|petra@privatescan.nl

|Linda Meijer
| x
|linda@privatescan.nl

|Wout Lansink
| Hoofd afdeling Hernia
|wout@privatescan.nl
|===

=== Afspraken

=== Glossarium
