
=== Introduction

De PrivateScan Factuur Verwerking Tool is ontwikkeld om het proces van factuurverwerking te automatiseren en te versnellen. Het primaire doel is om de status van orderregels in het CRM systeem bij te werken op basis van ingescande facturen.

De tool biedt de volgende voordelen:
* Automatisering van handmatige processen
* Vermindering van menselijke fouten
* Versnelling van factuurverwerking
* Consistente status updates in het CRM systeem

=== Opdrachtomschrijving / Businessdoelstellingen

TODO: Beschrijf hier de specifieke business doelstellingen en opdrachtomschrijving.

=== Doelgroep
Deze tool is specifiek ontwikkeld voor medewerkers van PrivateScan die verantwoordelijk zijn voor het verwerken van facturen en het bijwerken van CRM status.

=== Wie werkt er aan dit project?

Vast team samenstelling bestaat uit het onderstaande schema.
Vaak zetten we er ook een flexibele schil naast, die vaak niet aanwezig zijn met gezamenlijke sessies.

[cols="1,1,1,1"]
|===
|Team Privatescan |Rol(len)| e-mailadres |Telefoonnummer

|Mark klaucke
|Productowner(PO)
|link:mailto:mark.klaucke@digi4you.nl[mark]
|

|Mark Bulthuis
|Architect
|mark.bulthuis@mbsoftware.nl
|0611251149

|===

*Stakeholders*

[cols="1,1,1"]
|===
|Klant |Rol(len)| e-mailadres

|Frank Hefti
|Eigenaar Privatescan B.V.
|link:mailto:frank@privatescan.nl[frank@privatescan.eu]

|Petra Nijhof
| x
|petra@privatescan.nl

|Linda Meijer
| x
|linda@privatescan.nl

|===

=== Afspraken

=== Glossarium
