PrivateScan CRM

=== Introduction

De PrivateScan CRM is ontwikkeld als vervanging van het verouderde SugarCRM-systeem. Door de technische beperkingen en het gebrek aan ontwikkelmogelijkheden in het oude systeem was verdere doorontwikkeling niet meer haalbaar.

Er is daarom bewust gekozen om het nieuwe systeem volledig vanaf de basis op te bouwen. Daarbij zijn waardevolle onderdelen uit SugarCRM hergebruikt waar zinvol, maar is tegelijkertijd gekozen voor een frisse, toekomstbestendige opzet waarmee we weer jaren vooruit kunnen.


=== Opdrachtomschrijving / Businessdoelstellingen

Opdracht komt voort uit advies rapport, zie onze share op de Citrix omgeving;: file:///P:/Healthcare%20Solution/Resultaten%20deelopdrachten/Deelopdracht%202/Adviesdocument%20CRM%20keuze.pdf

=== Doelgroep
De primaire doelgroep bestaat uit medewerkers van Privatescan die betrokken zijn bij het klantcontact, de planning van medische onderzoeken en de administratieve afhandeling. Denk hierbij aan:

* Frontoffice medewerkers – verantwoordelijk voor intake, communicatie met patiënten, en het plannen van afspraken.

* Backoffice personeel – belast met orderverwerking, facturatie en nazorg.

* Medisch coördinatoren – die overzicht houden over dossiers, specialisten en kliniekplanning. (geen toegang tot CRM), zal een los portaal krijgen)

* Patienten - los patient portaal (geen toegang tot CRM)

* Management – dat behoefte heeft aan inzicht in lopende aanvragen, doorlooptijden en conversiepercentages.

De gebruikers zijn overwegend niet technisch en verwachten een intuïtieve interface waarin ze snel overzicht krijgen over hun verantwoordelijkheden. Efficiëntie, foutpreventie en goede logging zijn van groot belang, mede vanwege het medische en privacygevoelige karakter van de dienstverlening.



=== Wie werkt er aan dit project?

Vast team samenstelling bestaat uit het onderstaande schema.
Vaak zetten we er ook een flexibele schil naast, die vaak niet aanwezig zijn met gezamenlijke sessies.

[cols="1,1,1,1"]
|===
|Team Privatescan |Rol(len)| e-mailadres |Telefoonnummer

|Mark klaucke
|Productowner(PO)
|link:mailto:mark.klaucke@digi4you.nl[mark]
|

|Mark Bulthuis
|Architect
|mark.bulthuis@mbsoftware.nl
|0611251149

|Mark Pinksteren
|UX designer
|link:mailto:mark@markyourmedia.nl[mark@markyourmedia.nl]
|?

|===

*Stakeholders*

[cols="1,1,1"]
|===
|Klant |Rol(len)| e-mailadres

|Frank Hefti
|Eigenaar Privatescan B.V.
|link:mailto:frank@privatescan.nl[frank@privatescan.eu]

|Petra Nijhof
| x
|petra@privatescan.nl

|Linda Meijer
| x
|linda@privatescan.nl

|Wout Lansink
| Hoofd afdeling Hernia
|wout@privatescan.nl
|===

=== Milestones en acceptatie criteria

==== LEAD

[ ] *Lead en contactpersoon entiteiten zijn compleet gedefinieerd*

* Alle relevante velden zijn aanwezig conform datamodel
* Validatie op verplichte velden is correct geïmplementeerd
* Contactpersoon is te koppelen of aan te maken vanuit de lead

[ ] *Workflow voor lead-proces is ingericht tot en orderbevestiging*

* Workflow bevat alle benodigde statussen: van binnenkomst tot orderbevestiging
* Activiteiten worden automatisch of handmatig aangemaakt op relevante momenten
* De volgende use cases / workflows dienen te werken:
** *Full body scan, acceptatiecriteria:*
*** Lead komt binnen op het bord van Privatescan.
** *Diagnoseformulier wordt ingevuld op hernia.nl, persoon heeft al MRI-beelden:*
*** Lead komt binnen op het bord Hernia.
*** Medewerker dient de lead zelf te slepen naar 'Adviseren met MRI beelden' (na koppelen contactpersoon).
** *Diagnoseformulier wordt ingevuld op hernia.nl en daarna vult de persoon een aanvraagformulier in voor MRI-scan:*
*** Eerste lead komt binnen op Hernia board.
*** Tweede lead komt binnen op Privatescan board.
*** Ondanks dat deze flow los binnenkomt, dient men dit eenvoudig te kunnen zien via de contactpersoon.
*** Hernia kan moeten wachten op de MRI-beelden. In het systeem moet dit eenvoudig te zien zijn en Hernia dient tijdig de flow op te kunnen pakken nadat de MRI-beelden zijn aangeleverd.

[ ] *Ontwerp van CRM-schermen is definitief (template opbouw / look en feel)*

* Alle schermen voor leadbeheer, contactpersonen, en anamnese zijn visueel en functioneel uitgewerkt
* Navigatie, veldopbouw en acties zijn afgestemd met stakeholders
* Ontwerp is goedgekeurd en als referentie vastgelegd voor ontwikkeling

[ ] *Test * Migratie van bestaande leads en contactpersonen is uitgevoerd*

* Filters bepalen voor over te nemen records (volgens vastgestelde filters)
* Gegevens zijn gemapt naar het nieuwe datamodel zonder dataverlies
* Resultaten zijn steekproefsgewijs gecontroleerd

[ ] *Anamnese wordt automatisch aangemaakt bij elke nieuwe lead*

* Nieuwe leads krijgen een nieuw anamnese-record op moment van conversie / koppeling met contactpersoon
* Anamnese is via het CRM-interface bewerkbaar
* Anamnese hoeft inhoudelijk nog niet compleet te zijn
* Anamnese moet in te zien zijn via lead en contactpersoon

==== LEAD ORDER

=== Glossarium
