CREATE DATABASE IF NOT EXISTS forms CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'formadmin'@'%' IDENTIFIED BY 'FUC16A-qsh(<d!io';
GRANT ALL PRIVILEGES ON forms.* TO 'formadmin'@'%';
FLUSH PRIVILEGES;
