#!/bin/bash
# Init Forms Database Script
# Reads FORMS_DB_PASSWORD from the container environment (set via docker-compose).
set -e

: "${FORMS_DB_PASSWORD:?FORMS_DB_PASSWORD env var is required}"

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS `${SUGARCRM_DB_DATABASE}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    CREATE USER IF NOT EXISTS '${SUGARCRM_DB_USERNAME}' IDENTIFIED BY '${FORMS_DB_PASSWORD}';
    ALTER USER '${SUGARCRM_DB_USERNAME}'@'%' IDENTIFIED BY '${FORMS_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON `${SUGARCRM_DB_DATABASE}`.*  TO '${SUGARCRM_DB_USERNAME}'@'%';
    FLUSH PRIVILEGES;
EOSQL
