CREATE DATABASE IF NOT EXISTS n8n_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'n8n_user'@'%' IDENTIFIED BY 'FUC16A-qsh(<d!io';
GRANT ALL PRIVILEGES ON n8n_db.* TO 'n8n_user'@'%';
FLUSH PRIVILEGES;
