<?php

use App\Models\Order;
use App\Models\SalesLead;
use App\Services\Ai\Context\LeadContextBuilder;
use App\Services\Ai\Context\OrderContextBuilder;
use App\Services\Ai\Context\PersonContextBuilder;
use App\Services\Ai\Context\SalesLeadContextBuilder;
use Webkul\Contact\Models\Person;
use Webkul\Lead\Models\Lead;

return [

    /*
    |--------------------------------------------------------------------------
    | AI Summary Subjects
    |--------------------------------------------------------------------------
    |
    | Every entity that shows an AI summary in its right-hand panel is registered
    | here. Adding a new one means: a context builder that describes which records
    | are relevant, a prompt in config/ai_prompts.php, and an entry below.
    |
    | The subject key is the morph alias used in ai_summaries.subject_type and in
    | the /admin/ai-summary/{subject}/{id} routes, so it must match the alias in
    | AdminServiceProvider::boot().
    |
    | Per-subject keys:
    |   model             - Eloquent model the summary is attached to.
    |   builder           - App\Services\Ai\Context\AiContextBuilder implementation.
    |   use_case          - key in config/ai_prompts.php holding prompt + LLM settings.
    |   payload_key       - name of the subject block in the payload; the prompt for this
    |                       use case refers to it by that name.
    |   prompt_version    - stored on every summary, bump it when the prompt changes.
    |   label             - Dutch noun used in flash messages and log lines.
    |   view/edit_permission - ACL keys checked before reading/refreshing a summary.
    |   generate_on_view  - generate lazily the first time someone opens the panel.
    |   owner_scoped      - mirror the entity's own access rule: refuse the summary when
    |                       the record belongs to a colleague the user may not see.
    |   stale_after_hours - refresh on view once the summary is older than this (0 = never).
    |   activity_limit    - max activities in the context payload.
    |   email_limit       - max e-mails in the context payload.
    |
    */

    'enabled' => filter_var(env('LLM_AI_SUMMARY_ENABLED', true), FILTER_VALIDATE_BOOLEAN),

    'scheduled_queue' => env('LLM_AI_SUMMARY_SCHEDULED_QUEUE', 'ai-summary-scheduled'),

    'defaults' => [
        'enabled'           => true,
        'prompt_version'    => 'v1',
        'owner_scoped'      => true,
        'generate_on_view'  => true,
        'stale_after_hours' => (int) env('LLM_AI_SUMMARY_STALE_AFTER_HOURS', 24),
        'activity_limit'    => (int) env('LLM_AI_SUMMARY_ACTIVITY_LIMIT', 12),
        'email_limit'       => (int) env('LLM_AI_SUMMARY_EMAIL_LIMIT', 6),
    ],

    'subjects' => [

        'leads' => [
            'model'            => Lead::class,
            'builder'          => LeadContextBuilder::class,
            'use_case'         => 'lead_summary',
            'payload_key'      => 'lead',
            'prompt_version'   => env('LLM_LEAD_SUMMARY_PROMPT_VERSION', 'v3'),
            'label'            => 'lead',
            'view_permission'  => 'leads.view',
            'edit_permission'  => 'leads.edit',
            'route'            => 'admin.leads.view',
            'enabled'          => filter_var(env('LLM_LEAD_SUMMARY_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
            // Leads are already generated by the observer and the daily refresh command.
            'generate_on_view' => false,
        ],

        'persons' => [
            'model'           => Person::class,
            'builder'         => PersonContextBuilder::class,
            'use_case'        => 'person_summary',
            'payload_key'     => 'person',
            'prompt_version'  => env('LLM_PERSON_SUMMARY_PROMPT_VERSION', 'v1'),
            'label'           => 'contactpersoon',
            'view_permission' => 'contacts.persons.view',
            'edit_permission' => 'contacts.persons.edit',
            'route'           => 'admin.contacts.persons.view',
            // Contacts are not owner-scoped in the CRM itself, so the summary is not either.
            'owner_scoped'    => false,
            'enabled'         => filter_var(env('LLM_PERSON_SUMMARY_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
            // A person spans every lead and order, so allow a wider window.
            'activity_limit'  => (int) env('LLM_PERSON_SUMMARY_ACTIVITY_LIMIT', 15),
        ],

        'orders' => [
            'model'           => Order::class,
            'builder'         => OrderContextBuilder::class,
            'use_case'        => 'order_summary',
            'payload_key'     => 'order',
            'prompt_version'  => env('LLM_ORDER_SUMMARY_PROMPT_VERSION', 'v1'),
            'label'           => 'order',
            'view_permission' => 'orders.view',
            'edit_permission' => 'orders.edit',
            'route'           => 'admin.orders.view',
            'enabled'         => filter_var(env('LLM_ORDER_SUMMARY_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
        ],

        'sales_leads' => [
            'model'           => SalesLead::class,
            'builder'         => SalesLeadContextBuilder::class,
            'use_case'        => 'sales_lead_summary',
            'payload_key'     => 'sales_lead',
            'prompt_version'  => env('LLM_SALES_LEAD_SUMMARY_PROMPT_VERSION', 'v1'),
            'label'           => 'sales lead',
            'view_permission' => 'sales-leads.view',
            'edit_permission' => 'sales-leads.edit',
            'route'           => 'admin.sales-leads.view',
            'enabled'         => filter_var(env('LLM_SALES_LEAD_SUMMARY_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
        ],

    ],

];
