=== Migratie plan

1. run reset_prod.sh (import van data, verwijderd alle bestaande)
2. Zet de bestanden voor email bijlage klaar
2b. Zorg dat de bestanden van suitecrm folder upload op de nieuwe server staan in folder /home/mbulthuis/upload
    Voer een scp uit:
scp /var/www/html/privatesuite/upload/37c10db2-a63d-7226-1f86-67eea4779991 \
/var/www/html/privatesuite/upload/58529127-b500-aeda-da0d-67eea47a0b53 \
/var/www/html/privatesuite/upload/2d920118-1784-5cfb-a3e3-67eea41567ba \
/var/www/html/privatesuite/upload/b224ae58-5794-fb05-8e14-67eea43a7e2f \
mbulthuis@178.251.28.76:/home/apps/migration/upload/
2b. sail artisan import:email-attachment-files
2c. verwijderen de oude upload files.


=== Calamiteitenplan

Het calamiteitenplan beschrijft wie in geval van nood bereikbaar is, op welke manier, en waarvoor zij verantwoordelijk zijn. Dit biedt duidelijkheid en handelingssnelheid bij technische of operationele incidenten.

**Contactpersonen bij calamiteiten**

==== IceHosting – Christian Bolster

E: info@icehosting.nl
T. +31 (0)53 700 9750
IceHosting B.V.
Josinkstraat 28
7547AB Enschede

Verantwoordelijk voor de hosting van twee cruciale services. Bereikbaar bij uitval van infrastructuur.

==== CODE 14 – Backup software-expertise
Indien zowel Mark K. als ondergetekende langdurig en plotseling wegvallen, kan contact worden opgenomen met:
Harm-Jan, CTO van CODE 14 in Rijssen.
Backup-expert met kennis van de softwarearchitectuur. Zij zijn ervaren met een Laravel stack, die hier is opgezet.

==== Steentjes
Speelt nog een tijdelijke rol in de hosting van de huidige SugarCRM Suite.
Contactgegevens zijn intern bekend. Alleen van toepassing zolang dit systeem nog operationeel is.


=== Afspraken

* **Backups & herstelprocedures**
Mogelijk bij IceHosting, nog geen definitieve afspraken over gemaakt.
Dient te gebeuren, voordat wij live gaan

* **Monitoring & foutdetectie**
Voor monitoring en foutanalyse zetten we Sentry in. Hiermee kunnen we technische issues vroegtijdig signaleren en gericht oplossen.

* **Versiebeheer & Continuous Integration**
Git en CI zijn ondergebracht in GitHub. Dit biedt overzichtelijke versiecontrole, pull requests, en geautomatiseerde tests bij elke wijziging.

