[supervisord]
nodaemon=true
logfile=/usr/share/nginx/html/storage/logs/supervisord.log
pidfile=/usr/share/nginx/html/storage/logs/supervisord.pid
childlogdir=/var/log/supervisor

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:php-fpm]
directory=/usr/share/nginx/html
command=php-fpm
autostart=true
autorestart=true
stderr_logfile=/var/log/php-fpm.err.log
stdout_logfile=/var/log/php-fpm.out.log

[program:nginx]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log

[program:cron]
command=cron -f
autostart=true
autorestart=true
stderr_logfile=/usr/share/nginx/html/storage/logs/cron.err.log
stdout_logfile=/usr/share/nginx/html/storage/logs/cron.out.log
user=www-data

[program:artisan-migrate]
directory=/usr/share/nginx/html
command=/usr/bin/env bash -c "sleep 8 && php artisan migrate --force"
autostart=true
autorestart=unexpected
exitcodes=0
stdout_logfile=/var/log/artisan-migrate.log
stderr_logfile=/var/log/artisan-migrate.err.log
user=www-data

[program:laravel-scheduler]
command=/usr/local/bin/php /usr/share/nginx/html/artisan schedule:work
directory=/usr/share/nginx/html
autostart=true
autorestart=true
user=www-data
stdout_logfile=/usr/share/nginx/html/storage/logs/scheduler.out.log
stderr_logfile=/usr/share/nginx/html/storage/logs/scheduler.err.log

