[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=0
pidfile=/usr/share/nginx/html/storage/logs/supervisord.pid
childlogdir=/var/log/supervisor

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:php-fpm]
directory=/usr/share/nginx/html
command=/bin/bash -c "/usr/local/sbin/php-fpm --fpm-config /usr/local/etc/php-fpm.conf --php-ini /usr/local/etc/php/php.ini --nodaemonize"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log

[program:cron]
command=/bin/bash -c "cron -f 2>&1 | /usr/share/nginx/html/.docker/json-logger.sh cron INFO"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:artisan-migrate]
directory=/usr/share/nginx/html
command=/usr/bin/env bash -c "sleep 8 && php artisan migrate --path=vendor/laravel/sanctum/database/migrations --force && php artisan migrate --force 2>&1 | /usr/share/nginx/html/.docker/json-logger.sh laravel-migration INFO"
autostart=true
autorestart=unexpected
exitcodes=0
user=www-data
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:laravel-scheduler]
command=/bin/bash -c "/usr/local/bin/php /usr/share/nginx/html/artisan schedule:work 2>&1 | /usr/share/nginx/html/.docker/json-logger.sh laravel-scheduler ERROR"
directory=/usr/share/nginx/html
autostart=true
autorestart=true
user=www-data
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

