<?php

namespace App\Enums;

enum PipelineStageDefaultKeys: int
{
    case PIPELINE_FIRST_STAGE_PRIVATESCAN_ID = 1;
    case PIPELINE_FIRST_STAGE_HERNIA_ID = 6;
    case PIPELINE_FIRST_STAGE_PRIVATESCAN_WORKFLOW_ID = 13;
    case PIPELINE_FIRST_STAGE_HERNIA_WORKFLOW_ID = 16;
    case PIPELINE_FIRST_STAGE_PRIVATESCAN_ORDER_ID = 30;
    case PIPELINE_FIRST_STAGE_HERNIA_ORDER_ID = 39;

}
