{{--See entity-selector.js, included by app.js ---}}

@props([
    'name' => 'entities',
    'label' => 'Geselecteerde items',
    'placeholder' => 'Zoek item...',
    'searchRoute' => null,
    'canAddNew' => false,
    'multiple' => true,
    'style' => 'default',
    'items' => [],
    'currentValue' => null,
    'currentLabel' => null,
    'eventName' => null,
])

@php
    $uniqueEvent = $eventName ?? ('entity-add-' . \Illuminate\Support\Str::uuid());

    // Convert currentValue and currentLabel to items format if provided
    $preSelectedItems = $items;
    if ($currentValue && $currentLabel) {
        $preSelectedItems = [
            [
                'id' => $currentValue,
                'name' => $currentLabel,
            ]
        ];
    }

    $jsonConfig = json_encode([
        'name' => $name,
        'label' => $label,
        'placeholder' => $placeholder,
        'searchRoute' => $searchRoute,
        'canAddNew' => $canAddNew,
        'multiple' => $multiple,
        'style' => $style,
        'eventName' => $uniqueEvent,
        'items' => $preSelectedItems,
    ], JSON_HEX_APOS);
@endphp

<div class="w-full space-y-3" id="entity-selector-{{ $name }}"
     data-entity-config='{{ $jsonConfig }}'>
    <!-- Content will be dynamically generated by JavaScript -->
</div>
