[www]
user = www-data
group = www-data
access.format = "FPM: [%t] %m %{REQUEST_SCHEME}e://%{HTTP_HOST}e%{REQUEST_URI}e %f pid:%p took:%ds mem:%{mega}Mmb cpu:%C%% status:%s {%{REMOTE_ADDR}e|%{HTTP_USER_AGENT}e}"
catch_workers_output=yes
pm = dynamic
pm.max_children = 50
pm.start_servers = 8
pm.min_spare_servers = 4
pm.max_spare_servers = 12
listen = /run/fpm.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660
