name: Linting Tests

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development

permissions:
  contents: write

jobs:
  linting_tests:
    runs-on: ${{ matrix.operating-systems }}

    strategy:
      matrix:
        operating-systems: [ubuntu-latest]
        php-versions: ['8.5']

    name: PHP ${{ matrix.php-versions }} test on ${{ matrix.operating-systems }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer

      - name: Install Dependencies
        run: composer install

      - name: Run Duster
        run: ./vendor/bin/duster lint --no-interaction || true

      - name: Commit Linted Files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: applied duster changes"
