name: Cleanup GHCR images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Reinig GHCR container images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: privatescanbv
          token: ${{ secrets.GHCR_PAT }}
          image-names: |
            krayin-laravel-crm/krayincrm
            krayin-laravel-crm/crmsyncn8n
          image-tags: "!latest"
          keep-n-most-recent: 3
          dry-run: false
          tag-selection: both
          cut-off: '2w'
          rust-log: info
      - name: Verwijder ongetagde GHCR images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: privatescanbv
          token: ${{ secrets.GHCR_PAT }}
          image-names: |
            krayin-laravel-crm/krayincrm
            krayin-laravel-crm/crmsyncn8n
          tag-selection: untagged
          dry-run: false
          cut-off: '4d'
          rust-log: info
