name: Build and push Docker image

on:
  push:
    branches: ["development"]

permissions:
  contents: read
  packages: write

jobs:
  docker-crm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # for building frontend, will be copied to docker later
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build and push CRM image using build_image.sh
        run: |
          chmod +x ./build_image.sh
          ./build_image.sh

  docker-keycloak:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push sync flows image using build_image_keycloak.sh
        run: |
          chmod +x ./build_image_keycloak.sh
          echo "Building keycloak image..."
          ./build_image_keycloak.sh
          echo "Keycloak image build completed successfully"
